---
name: Build
on:
  workflow_dispatch:
    inputs:
      git_ref:
        description: Emacs git ref to build
        required: true
        default: "master"
      git_sha:
        description: Override Emacs git commit SHA to build
        required: false
      builder_ref:
        description: "Git ref to checkout of build-emacs-for-macos"
        required: true
        default: "master"
      builder_args:
        description: Custom arguments passed to build script
        required: false
        default: "--no-relink-eln-files"
      os:
        description: 'Runner OS ("macos-10.15" or "macos-11")'
        required: true
        default: "macos-10.15"
      test_build_name:
        description: "Test build name"
        required: false
        default: ""
      test_release_type:
        description: "prerelease or draft"
        required: false
        default: ""

jobs:
  prepare:
    name: Prepare
    uses: jimeh/emacs-builds/.github/workflows/_prepare.yml@main
    with:
      builder_ref: ${{ github.event.inputs.builder_ref }}
    secrets:
      TAP_REPO_TOKEN: ${{ secrets.TAP_REPO_TOKEN }}

  build:
    name: Build
    needs: [prepare]
    uses: jimeh/emacs-builds/.github/workflows/_build.yml@main
    with:
      os: macos-10.15
      git_ref: ${{ github.event.inputs.git_ref }}
      git_sha: ${{ github.event.inputs.git_sha }}
      build_args: ${{ github.event.inputs.builder_args }}
      test_build_name: ${{ github.event.inputs.test_build_name }}
      test_release_type: ${{ github.event.inputs.test_release_type }}
    secrets:
      APPLE_DEVELOPER_CERTIFICATE_P12_BASE64: ${{ secrets.APPLE_DEVELOPER_CERTIFICATE_P12_BASE64 }}
      APPLE_DEVELOPER_CERTIFICATE_PASSWORD: ${{ secrets.APPLE_DEVELOPER_CERTIFICATE_PASSWORD }}
      KEYCHAIN_PASSWORD: ${{ secrets.KEYCHAIN_PASSWORD }}
      AC_USERNAME: ${{ secrets.AC_USERNAME }}
      AC_PASSWORD: ${{ secrets.AC_PASSWORD }}
      AC_PROVIDER: ${{ secrets.AC_PROVIDER }}
      AC_SIGN_IDENTITY: ${{ secrets.AC_SIGN_IDENTITY }}
      TAP_REPO_TOKEN: ${{ secrets.TAP_REPO_TOKEN }}

  release:
    name: Release
    needs: [build]
    uses: jimeh/emacs-builds/.github/workflows/_release.yml@main
    with:
      plan_artifact: build-plan
      dmg_artifact: dmg
    secrets:
      TAP_REPO_TOKEN: ${{ secrets.TAP_REPO_TOKEN }}
