---
name: Update Metadata
concurrency: jimeh/emacs-builds/update-metadata
on:
  schedule:
    - cron: "0 0,12 * * *"
  workflow_dispatch:

jobs:
  update-metadata:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout tap repository main branch
        uses: actions/checkout@v2
        with:
          ref: meta
      - uses: actions/setup-go@v2
        with:
          go-version: 1.17
      - uses: actions/cache@v2
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('builder/**/go.sum') }}
          restore-keys: ${{ runner.os }}-go-
      - name: update total downloads shield JSON
        run: go run . badges downloads -o total-downloads/shield.json
      - name: commit and push changes to meta branch
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "chore(meta): update metadata files"
          commit_user_name: github-actions[bot]
          commit_user_email: github-actions[bot]@users.noreply.github.com
          commit_author: >-
            github-actions[bot] <github-actions[bot]@users.noreply.github.com>
          skip_dirty_check: false
